sudo docker rm $(sudo docker ps -a -q)

sudo docker rmi m0rf30/pacur-archlinux
sudo docker rmi m0rf30/pacur-amazonlinux-2016.09
sudo docker rmi m0rf30/pacur-amazonlinux-2017.03
sudo docker rmi m0rf30/pacur-amazonlinux-2017.09
sudo docker rmi m0rf30/pacur-amazonlinux-2017.12
sudo docker rmi m0rf30/pacur-amazonlinux-1
sudo docker rmi m0rf30/pacur-amazonlinux-2
sudo docker rmi m0rf30/pacur-centos-6
sudo docker rmi m0rf30/pacur-centos-7
sudo docker rmi m0rf30/pacur-centos-8
sudo docker rmi m0rf30/pacur-debian-jessie
sudo docker rmi m0rf30/pacur-debian-stretch
sudo docker rmi m0rf30/pacur-debian-wheezy
sudo docker rmi m0rf30/pacur-debian-buster
sudo docker rmi m0rf30/pacur-fedora-21
sudo docker rmi m0rf30/pacur-fedora-22
sudo docker rmi m0rf30/pacur-fedora-23
sudo docker rmi m0rf30/pacur-fedora-24
sudo docker rmi m0rf30/pacur-fedora-25
sudo docker rmi m0rf30/pacur-fedora-26
sudo docker rmi m0rf30/pacur-fedora-27
sudo docker rmi m0rf30/pacur-fedora-28
sudo docker rmi m0rf30/pacur-fedora-29
sudo docker rmi m0rf30/pacur-fedora-30
sudo docker rmi m0rf30/pacur-fedora-31
sudo docker rmi m0rf30/pacur-fedora-32
sudo docker rmi m0rf30/pacur-genkey
sudo docker rmi m0rf30/pacur-opensuse-tumbleweed
sudo docker rmi m0rf30/pacur-oraclelinux-7
sudo docker rmi m0rf30/pacur-oraclelinux-8
sudo docker rmi m0rf30/pacur-ubuntu-precise
sudo docker rmi m0rf30/pacur-ubuntu-trusty
sudo docker rmi m0rf30/pacur-ubuntu-vivid
sudo docker rmi m0rf30/pacur-ubuntu-wily
sudo docker rmi m0rf30/pacur-ubuntu-xenial
sudo docker rmi m0rf30/pacur-ubuntu-yakkety
sudo docker rmi m0rf30/pacur-ubuntu-zesty
sudo docker rmi m0rf30/pacur-ubuntu-artful
sudo docker rmi m0rf30/pacur-ubuntu-bionic
sudo docker rmi m0rf30/pacur-ubuntu-cosmic
sudo docker rmi m0rf30/pacur-ubuntu-disco
sudo docker rmi m0rf30/pacur-ubuntu-eoan
sudo docker rmi m0rf30/pacur-ubuntu-focal
sudo docker rmi m0rf30/pacur-ubuntu-groovy
sudo docker rmi base/archlinux
sudo docker rmi archlinux/base
sudo docker rmi amazonlinux:2016.09
sudo docker rmi amazonlinux:2017.03
sudo docker rmi amazonlinux:2017.09
sudo docker rmi amazonlinux:2017.12
sudo docker rmi amazonlinux:1
sudo docker rmi amazonlinux:2
sudo docker rmi centos:6
sudo docker rmi centos:7
sudo docker rmi centos:8
sudo docker rmi debian:jessie
sudo docker rmi debian:stretch
sudo docker rmi debian:wheezy
sudo docker rmi debian:buster
sudo docker rmi fedora:21
sudo docker rmi fedora:22
sudo docker rmi fedora:23
sudo docker rmi fedora:24
sudo docker rmi fedora:25
sudo docker rmi fedora:26
sudo docker rmi fedora:27
sudo docker rmi fedora:28
sudo docker rmi fedora:29
sudo docker rmi fedora:30
sudo docker rmi fedora:31
sudo docker rmi fedora:32
sudo docker rmi opensuse:tubleweed
sudo docker rmi oraclelinux:7
sudo docker rmi oraclelinux:8
sudo docker rmi ubuntu:precise
sudo docker rmi ubuntu:trusty
sudo docker rmi ubuntu:vivid
sudo docker rmi ubuntu:wily
sudo docker rmi ubuntu:xenial
sudo docker rmi ubuntu:yakkety
sudo docker rmi ubuntu:zesty
sudo docker rmi ubuntu:artful
sudo docker rmi ubuntu:bionic
sudo docker rmi ubuntu:cosmic
sudo docker rmi ubuntu:disco
sudo docker rmi ubuntu:eoan
sudo docker rmi ubuntu:focal
sudo docker rmi ubuntu:groovy

sudo docker rmi $(sudo docker images -q -f dangling=true)
