 docker rm $(sudo docker ps -a -q)
 docker rmi m0rf30/pacur-archlinux
 docker rmi m0rf30/pacur-amazonlinux-1
 docker rmi m0rf30/pacur-amazonlinux-2
 docker rmi m0rf30/pacur-centos-7
 docker rmi m0rf30/pacur-debian-stretch
 docker rmi m0rf30/pacur-debian-wheezy
 docker rmi m0rf30/pacur-debian-buster
 docker rmi m0rf30/pacur-fedora-30
 docker rmi m0rf30/pacur-fedora-31
 docker rmi m0rf30/pacur-genkey
 docker rmi m0rf30/pacur-oraclelinux-7
 docker rmi m0rf30/pacur-ubuntu-xenial
 docker rmi m0rf30/pacur-ubuntu-bionic
 docker rmi m0rf30/pacur-ubuntu-eoan
 docker rmi base/archlinux
 docker rmi archlinux/base
 docker rmi amazonlinux:1
 docker rmi amazonlinux:2
 docker rmi centos:7
 docker rmi debian:stretch
 docker rmi debian:buster
 docker rmi fedora:30
 docker rmi fedora:31
 docker rmi oraclelinux:7
 docker rmi ubuntu:xenial
 docker rmi ubuntu:bionic
 docker rmi ubuntu:eoan
 docker rmi $(sudo docker images -q -f dangling=true)
